### ISSUE TITLE
Unterminated string at line 1 column 507905 path $.content

### ISSUE THREAD

**Issue by Abasing** [Artillex-Studios/AxTrade#9]
Plugin Version: 1.7.1
Server Software: Paper
Server Version: 1.20.1 "Latest Build to this date"

[22:01:15 INFO]: [AxTrade] Enabling AxTrade v1.7.1
[22:01:16 INFO]: ╠ Downloading en_us language files..
[22:02:02 WARN]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 507905 path $.content
[22:02:02 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1229)
[22:02:02 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1124)
[22:02:02 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1034)
[22:02:02 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:969)
[22:02:02 WARN]:        at AxTrade-1.7.1.jar//com.artillexstudios.axtrade.lang.LanguageManager.reload(LanguageManager.java:49)
[22:02:02 WARN]:        at AxTrade-1.7.1.jar//com.artillexstudios.axtrade.AxTrade.enable(AxTrade.java:59)
[22:02:02 WARN]:        at AxTrade-1.7.1.jar//com.artillexstudios.axtrade.libs.axapi.AxPlugin.onEnable(AxPlugin.java:111)
[22:02:02 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[22:02:02 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[22:02:02 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[22:02:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[22:02:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
[22:02:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
[22:02:02 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[22:02:02 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[22:02:02 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[22:02:02 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[22:02:02 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[22:02:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[22:02:02 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 507905 path $.content
[22:02:02 WARN]:        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657)
[22:02:02 WARN]:        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1042)
[22:02:02 WARN]:        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
[22:02:02 WARN]:        at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747)
[22:02:02 WARN]:        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791)
[22:02:02 WARN]:        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725)
[22:02:02 WARN]:        at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007)
[22:02:02 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1214)
[22:02:02 WARN]:        ... 18 more
[22:02:02 INFO]: [AxTrade] Hooked into Vault!
[22:02:03 INFO]: [AxTrade] Loaded plugin!

**Comment by Abasing** [comment]
Now plugin is unable to load:

[00:44:38 INFO]: [AxVaults] Enabling AxVaults v2.1.0
[00:44:39 INFO]: [AxVaults] Loaded plugin!
[00:44:39 INFO]: [AxTrade] Enabling AxTrade v1.7.1
[00:44:40 ERROR]: Error occurred while enabling AxTrade v1.7.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/artillexstudios/axtrade/libs/axapi/libs/caffeine/caffeine/cache/Caffeine
        at com.artillexstudios.axtrade.libs.axapi.utils.StringUtils.<clinit>(StringUtils.java:53) ~[AxTrade-1.7.1.jar:?]
        at com.artillexstudios.axtrade.lang.LanguageManager.reload(LanguageManager.java:39) ~[AxTrade-1.7.1.jar:?]
        at com.artillexstudios.axtrade.AxTrade.enable(AxTrade.java:59) ~[AxTrade-1.7.1.jar:?]
        at com.artillexstudios.axtrade.libs.axapi.AxPlugin.onEnable(AxPlugin.java:111) ~[AxTrade-1.7.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.artillexstudios.axtrade.libs.axapi.libs.caffeine.caffeine.cache.Caffeine
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 16 more
[00:44:40 INFO]: [AxTrade] Disabling AxTrade v1.7.1

**Comment by BenceX100** [comment]
These should be fixed for some time at this point, but feel free to reopen this if it still happens.
